---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0505, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Float-DoubleDouble
no_index:
  directory:
    - t
    - inc
requires:
  Math::NV: '0.02'
resources:
  repository: https://github.com/sisyphus/data-float-doubledouble.git
version: '1.08'

